operator:
  enabled: true
  image:
    repository: kubesphereon/kube-events-operator
    tag: "" # If unset use v+ .Chart.appVersion
    pullPolicy: IfNotPresent
  configReloader:
    image: jimmidyson/configmap-reload:v0.7.1
  affinity: {}
  nodeSelector: {}
  tolerations: {}
  resources: {}
#    limits:
#      cpu: 200m
#      memory: 200Mi
#    requests:
#      cpu: 20m
#      memory: 20Mi
  # Additional volumes on the Deployment definition.
  volumes: []
  # Additional volumeMounts on the Deployment definition.
  volumeMounts: []
  serviceAccount:
    create: true
    name: ""
  # If true, just clean up cr but not crd
  cleanupAllCustomResources: false
  kubectlImage: docker.io/bitnami/kubectl:1.14.1

exporter:
  enabled: true
  image:
    repository: kubesphereon/kube-events-exporter
    tag: "" # If unset use v+ .Chart.appVersion
    pullPolicy: IfNotPresent
  affinity: {}
  nodeSelector: {}
  tolerations: {}
  resources: {}
#    limits:
#      cpu: 200m
#      memory: 500Mi
#    requests:
#      cpu: 20m
#      memory: 50Mi
  # Additional volumes on the output Deployment definition.
  volumes: []
  # Additional volumeMounts on the output Deployment definition.
  volumeMounts: []
  sinks:
    stdout:
      enabled: true
    additionalWebhooks: []
    # - url:
    #   service:
    #     namespace:
    #     name:
    #     port:
    #     path:

ruler:
  enabled: true
  replicas: 2
  image:
    repository: kubesphereon/kube-events-ruler
    tag: "" # If unset use v+ .Chart.appVersion
    pullPolicy: IfNotPresent
  affinity: {}
  nodeSelector: {}
  tolerations: {}
  resources: {}
#    limits:
#      cpu: 500m
#      memory: 500Mi
#    requests:
#      cpu: 50m
#      memory: 50Mi
  # Additional volumes on the output Deployment definition.
  volumes: []
  # Additional volumeMounts on the output Deployment definition.
  volumeMounts: []
  ruleNamespaceSelector: {}
  ruleSelector: {}
  sinks:
    alertmanagers:
    - namespace: kubesphere-monitoring-system
      name: alertmanager-operated
    # webhooks:
    # - type:
    #   url:
    #   service:
    #     namespace:
    #     name:
    #     port:
    #     path:
    ## 'stdout' sink type can be either 'notification' or 'alert'
    # stdout:
    #   type: notification
rule:
  createDefaults: true
  overrideDefaults: false

# Set timezone env variable to be set in containers
# timezone: "America/Toronto"
